spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password: roc
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always
      data-locations: classpath:db/import.sql
#      schema-locations: classpath:db/schema.sql
      platform: h2
